use QLDT

-- 6.a Thông tin GV Phản biện
-- HỌ TÊN, HỌC VỊ, HỌC HÀM, ĐIỆN THOẠI, ĐỊA CHỈ
-- GV_PBDT - GIAOVIEn - GV_HV_CN - HOCVI - HOCHAM
GO
CREATE VIEW V_GV_PB
AS
SELECT DISTINCT GV.TENGV, _GVHV.TENHV, HH.TENHH, GV.SODT, GV.DIACHI
FROM HOCHAM HH, GIAOVIEN GV, 
(SELECT _GV_HV.MSGV, HV.TENHV
    FROM 
        (
            SELECT PB.MSGV, GVHV.MSHV 
            FROM GV_PBDT PB
            LEFT JOIN GV_HV_CN GVHV
            ON PB.MSGV=GVHV.MSGV
        ) as _GV_HV 
    LEFT JOIN HOCVI HV ON _GV_HV.MSHV = HV.MSHV) as _GVHV
WHERE _GVHV.MSGV = GV.MSGV
AND GV.MSHH = HH.MSHH

-- 6.b Thông tin hội đồng chấm đề tài
-- TÊN ĐỀ TÀI, MÃ SỐ HỘI ĐỒNG, PHÒNG, NGÀY HỘI ĐỒNG, THỜI GIAN BẮT ĐẦU, TÊN CHỦ TỊCH HỘI ĐỒNG
-- DETAI - HOIDONG - HD_DT - GIAOVIEN
GO
CREATE VIEW V_HD_DT
AS
SELECT DT.TENDT, HD.MSHD, HD.PHONG, HD.NGAYHD, HD.TGBD, GV.TENGV as CHUTICH
FROM DETAI DT, HOIDONG HD, HOIDONG_DT HDDT, GIAOVIEN GV
WHERE DT.MSDT = HDDT.MSDT
AND HDDT.MSHD = HD.MSHD
AND HD.MSGV = GV.MSGV

-- 6.c Thông tin điểm đề tài. fixed(2)
-- MÃ SỐ ĐỀ TÀI, TÊN ĐỀ TÀI, MÃ SỐ HỘI ĐỒNG, QUYẾT ĐỊNH, ĐIỂM
-- DETAI - HOIDONG - HOIDONG_DT
GO
CREATE VIEW V_DIEM_DT
AS
SELECT DT.MSDT, DT.TENDT, HD.MSHD, HDDT.QUYETDINH, [dbo].[ListAVG](DT.MSDT) as DIEM
FROM DETAI DT, HOIDONG HD, HOIDONG_DT HDDT
WHERE DT.MSDT = HDDT.MSDT
AND HD.MSHD = HDDT.MSHD


--- Showing View's Data.
-- 6.a
GO
SELECT *
FROM [QLDT].[dbo].[V_GV_PB]

-- 6.b
GO
SELECT *
FROM [QLDT].[dbo].[V_HD_DT]

-- 6.c
GO
SELECT *
FROM [QLDT].[dbo].[V_DIEM_DT]

-- CLEAR
GO
DROP VIEW V_GV_PB
DROP VIEW V_HD_DT
DROP VIEW V_DIEM_DT

GO
use master
