-- LAB_3

use QLDT
--- 6.12
--- Creating View.
CREATE VIEW V_GIAOVIEN
AS
SELECT MSGV, TENGV
FROM GIAOVIEN
WHERE MSSH = 1

--- Showing View's Data.
SELECT TOP(100) [MSGV],[TENGV]
FROM [QLDT].[dbo].[V_GIAOVIEN]

SELECT *
FROM GIAOVIEN

--- 8.2
--- CREATE USERS.
CREATE LOGIN L1 WITH PASSWORD = '@Str0ng@P4ssWorD'
CREATE USER U1 FOR LOGIN L1

CREATE LOGIN L2 WITH PASSWORD = '@Str0ng@P4ssWorD'
CREATE USER U2 FOR LOGIN L2

CREATE LOGIN L3 WITH PASSWORD = '@Str0ng@P4ssWorD'
CREATE USER U3 FOR LOGIN L3

CREATE LOGIN L4 WITH PASSWORD = '@Str0ng@P4ssWorD'
CREATE USER U4 FOR LOGIN L4

CREATE LOGIN L5 WITH PASSWORD = '@Str0ng@P4ssWorD'
CREATE USER U5 FOR LOGIN L5

CREATE LOGIN L6 WITH PASSWORD = '@Str0ng@P4ssWorD'
CREATE USER U6 FOR LOGIN L6

--- CREATE ROLES.
CREATE ROLE R1
CREATE ROLE R2
CREATE ROLE R3

--- ADD ROLE MEMBERS.
EXEC sp_addrolemember R1,U1

EXEC sp_addrolemember R2,U2
EXEC sp_addrolemember R2,U3

EXEC sp_addrolemember R3,U4
EXEC sp_addrolemember R3,U5
EXEC sp_addrolemember R3,U6

--- ADD ROLES TO ADMIN


--- 9
--- CREATE TABLES.

-- T1: GIAOVIEN
-- T2: HOIDONG
-- T3: SINHVIEN

-- U1, U2, U3 ( Bai 8).

--- GRANT U1 => T1, T3
GRANT SELECT, DELETE ON GIAOVIEN TO U1
GRANT SELECT, DELETE ON SINHVIEN TO U1

--- GRANT U2 => T2
GRANT UPDATE, DELETE ON HOIDONG TO U2

--- GRANT U3 => T1, T2, T3
GRANT INSERT ON HOIDONG TO U3
GRANT INSERT ON HOIDONG TO U3
GRANT INSERT ON HOIDONG TO U3

--- DENY U1 => T1, T2
DENY INSERT ON GIAOVIEN TO U1
DENY INSERT ON HOIDONG TO U1

--- DENY U2 => T3
DENY DELETE ON SINHVIEN TO U2



