
use QLSACH
go

-- User
CREATE LOGIN L1 WITH PASSWORD = '@Str4ng@P4ssWorD'
CREATE USER US1 FOR LOGIN L1

CREATE LOGIN L2 WITH PASSWORD = '@Str4ng@P4ssWorD'
CREATE USER US2 FOR LOGIN L2

CREATE LOGIN L3 WITH PASSWORD = '@Str4ng@P4ssWorD'
CREATE USER US3 FOR LOGIN L3

CREATE LOGIN L4 WITH PASSWORD = '@Str4ng@P4ssWorD'
CREATE USER US4 FOR LOGIN L4

CREATE LOGIN L5 WITH PASSWORD = '@Str4ng@P4ssWorD'
CREATE USER US5 FOR LOGIN L5

CREATE LOGIN L6 WITH PASSWORD = '@Str4ng@P4ssWorD'
CREATE USER US6 FOR LOGIN L6

-- Role
GO
CREATE ROLE R1
CREATE ROLE R2
CREATE ROLE R3

-- User -> Role
GO
--- r1 -> us1
--- r2 -> us2, us3
--- r3 -> us4, us5 ,us6
EXEC sp_addrolemember R1,US1

EXEC sp_addrolemember R2,US2
EXEC sp_addrolemember R2,US3

EXEC sp_addrolemember R3,US4
EXEC sp_addrolemember R3,US5
EXEC sp_addrolemember R3,US6

-- Authorization
GO
--- GRANT:
---- US1 SELECT, DELETE TACGIA
---- US2 SELECT         TACGIA
---- US3 INSERT         SACH
GRANT SELECT, DELETE TACGIA TO US1
GRANT SELECT TACGIA TO US2
GRANT INSERT SACH TO US3

--- DENY:
---- US1 DELETE         NXB
---- US3 INSERT         NXB
DENY DELETE NXB TO US1
DENY INSERT NXB TO US3

--- REVOKE:
---- US1 DELETE         TACGIA
---- US3 INSERT         SACH
REVOKE DELETE TACGIA FROM US1
REVOKE INSERT SACH FROM US3

---
go
use master
